### ISSUE TITLE
Crash when bringing up the map in a basement

### ISSUE THREAD

**Issue by melville** [gilmore606/ure#94]
Looks like the background color of the terrain is null somehow.

```PLAYER: actiontime 0.047621727   cmd: MAP
Exception in thread "main" java.lang.NullPointerException
	at ure.render.URendererOGL.addQuad(URendererOGL.java:470)
	at ure.render.URendererOGL.addQuad(URendererOGL.java:420)
	at ure.render.URendererOGL.drawRect(URendererOGL.java:311)
	at ure.ui.modals.UModalMap.drawContent(UModalMap.java:27)
	at ure.ui.modals.UModal.draw(UModal.java:130)
	at ure.render.URendererOGL.render(URendererOGL.java:247)
	at ure.render.URendererOGL.render(URendererOGL.java:249)
	at ure.render.URendererOGL.render(URendererOGL.java:237)
	at ure.sys.UCommander.gameLoop(UCommander.java:435)
	at ure.examplegame.ExampleGame.startUp(ExampleGame.java:119)
	at ure.ExampleMain.main(ExampleMain.java:9)```

**Comment by gilmore606** [comment]
fixed, i forgot to give 'ladder' a bgcolor in glyphed
